print("What's your name?",)
name = input()
print("How old are you?",)
age = input()
print("How tall are you?",)
height = input()
print("How much do you weight?",)
weight = input()

print("So, you're name is %r, you're %r old, %r tall and %r heavy." % (name, age, height, weight))